export const Sectors = [
  "Aviation",
  "Agriculture",
  "Automotive",
  "Banking & Finance",
  "Software",
  "Bio-technology",
  "Chemicals",
  "Construction",
  "Legal",
  "E-commerce",
  "Fashion",
  "Consumer Goods",
  "Education",
  "Energy & Utilities",
  "Healthcare",
  "Hospitality & Tourism",
  "Information Technology",
  "Insurance",
  "Manufacturing",
  "Media & Entertainment",
  "Pharmaceuticals",
  "Real Estate",
  "Retail",
  "Telecommunications",
  "Transportation & Logistics",
  "Government & Public sector",
  "Non-profit/NGO",
  "Aerospace",
  "Defense",
];
