name: CD
on:
  push:
    branches: [main]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  create-version-pr-or-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 #
          persist-credentials: false
      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
  run-tests:
    needs: create-version-pr-or-release
    uses: "./.github/workflows/test.yaml"
    secrets: inherit
  deploy-to-staging:
    needs: run-tests
    uses: "./.github/workflows/deploy.yaml"
    secrets: inherit
    with:
      render-env: ${{ vars.RENDER_STAGING_ENV }}
      github-env: "staging"
  deploy-to-production:
    needs: run-tests
    uses: "./.github/workflows/deploy.yaml"
    secrets: inherit
    with:
      render-env: ${{ vars.RENDER_PRODUCTION_ENV }}
      github-env: "production"
